package gov.ca.cwds.cm.service.dto;

import static gov.ca.cwds.data.persistence.cms.CmsPersistentObject.CMS_ID_LEN;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import gov.ca.cwds.rest.api.Response;
import gov.ca.cwds.rest.validation.Date;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDate;

@Data
@EqualsAndHashCode(callSuper = false)
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
@SuppressWarnings({"squid:S3437"})
public class SafetyAlertDTO extends BaseDTO implements Response {

  private static final long serialVersionUID = 8017343478308334185L;

  @NotNull
  @Size(max = 4)
  @ApiModelProperty(
    value =
        "ACT_GOVERNMENT_ENTITY_TYPE - The system generated number which "
            + "represents the specific county (e.g., Alameda, Fresno, Merced, "
            + "Sacramento, etc.) within the state of California that created the "
            + "Safety Alert.  The selection choices will be provided by the "
            + "Government Entity Type code table. "
            + "Additional info can be reached from system-codes resource by 'GVR_ENTC' key.",
    example = "1068"
  )
  private Short activationGovermentEntityType;

  @NotNull
  @Date
  @ApiModelProperty(
    value = "ACTIVATION_DATE - The date the Safety Alert was effective.",
    example = "2013-01-28"
  )
  private LocalDate activationDate;

  @Size(max = 10)
  @ApiModelProperty(
    value =
        "ACTIVATION_EXPLANATION_TEXT - A narrative explanation for activating the Safety "
            + "Alert. This is the ID from LONG_TXT entity type which uniquely identifies "
            + "a specific occurrence of user defined text.",
    example = "8Dz06wW0X5"
  )
  private String activationExplanationTextId;

  @NotNull
  @Size(min = CMS_ID_LEN, max = CMS_ID_LEN)
  @ApiModelProperty(value = "Child Client ID", example = "BKk7CHj01Y")
  private String clientId;

  @NotNull
  @Size(max = 4)
  @ApiModelProperty(
    value =
        "ACTIVATION_REASON_TYPE - This code represents the reason the Safety "
            + "Alert was created. The selection choices will be provided by "
            + "the Safety Alert Activation Reason Type code table."
            + "Additional info can be reached from system-codes resource by 'ACTV_RNC' key.",
    example = "6401"
  )
  private Short activationReasonType;

  @Size(max = 4)
  @ApiModelProperty(
    value =
        "DEACT_GOVERNMENT_ENTITY_TYPE - The system generated number which represents the "
            + "specific county (e.g., Alameda, Fresno, Merced, Sacramento, etc.) within "
            + "the state of California that deactivated the Safety Alert.  The selection "
            + "choices will be provided by the Government Entity Type code table."
            + "Additional info can be reached from system-codes resource by 'GVR_ENTC' key.",
    example = "1068"
  )
  private Short deactivationGovermentEntityType;

  @Date
  @ApiModelProperty(
    value = "DEACTIVATION_DATE - The date the Safety Alert was deactivated.",
    example = "2013-01-28"
  )
  private LocalDate deactivationDate;

  @Size(max = 10)
  @ApiModelProperty(
    value =
        "DEACTIVATION_EXPLANATION_TEXT - A narrative explanation for"
            + " deactivating the Safety Alert. This is the ID from "
            + "LONG_TXT entity type which uniquely identifies a specific "
            + "occurrence of user defined text.",
    example = "0Wqj8l901w"
  )
  private String deactivationExplanationTextId;

  @NotNull
  @Size(max = 10)
  @ApiModelProperty(
    value =
        "THIRD_ID - This is a system generated unique number that supplements user "
            + "supplied data in the primary key. The Third ID attribute will be used "
            + "as part of the new Primary Key in combination with user supplied data. "
            + "It will also be used alone as a separate key for direct access. This Third "
            + "ID is composed of a base 62 Creation Timestamp and the STAFF_PERSON ID "
            + "(a sequential 3 digit base 62 number generated by the system).",
    example = "0000000000"
  )
  private String thirdId;
}
