package gov.ca.cwds.cm.service.mapper;

import gov.ca.cwds.cm.service.dto.ClientDTO;
import gov.ca.cwds.data.legacy.cms.entity.Client;
import org.mapstruct.Mapper;
import org.mapstruct.MapperConfig;
import org.mapstruct.Mapping;
import org.mapstruct.MappingInheritanceStrategy;

/** @author CWDS TPT-3 Team */
@Mapper
@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG)
@FunctionalInterface
public interface ClientMapper {

  @Mapping(target = "messages", ignore = true)
  @Mapping(target = "commentDescription", source = "commentDescription")
  @Mapping(target = "estimatedDobCode", source = "estimatedDobCode")
  @Mapping(target = "birthplaceVerifiedIndicator", source = "birthplaceVerifiedIndicator")
  @Mapping(target = "hispanicOriginCode", source = "hispanicOriginCode")
  @Mapping(target = "healthTxt", source = "healthSummaryText")
  @Mapping(target = "birthCity", source = "birthCity")
  @Mapping(target = "limitationOnSCPHealthIndicator", source = "limitationOnScpHealthIndicator")
  @Mapping(target = "healthCarePlanIndicator", source = "individualHealthCarePlanIndicator")
  @Mapping(target = "previouslyOtherDescription", source = "previousOtherDescription")
  @Mapping(target = "previouslyRegionalCenterIndicator", source = "previousRegionalCenterIndicator")
  @Mapping(target = "previouslyReceivedIndicator", source = "previousCaChildrenServiceIndicator")
  @Mapping(target = "currentlyOtherDescription", source = "currentlyOtherDescription")
  @Mapping(target = "childrenServIndicator", source = "currentCaChildrenServiceIndicator")
  @Mapping(target = "currentlyRegionalCenteerIndicator", source = "currentlyRegionalCenterIndicator")
  @Mapping(target = "adjudicatedDelinquentIndicator", source = "adjudicatedDelinquentIndicator")
  @Mapping(target = "deathDateVerifiedIndicator", source = "deathDateVerifiedIndicator")
  @Mapping(target = "emailAddr", source = "emailAddress")
  @Mapping(target = "soc158Ind", source = "soc158SealedClientIndicator")
  @Mapping(target = "tribalAncestryClientIndicator", source = "tribalAncestryClientIndicator")
  @Mapping(target = "tribalMemberVerificationIndicator", source = "tribalMembershipVerifcationIndicator")
  @Mapping(target = "deathPlace", source = "deathPlace")
  @Mapping(target = "zippyIndicator", source = "zippyCreatedIndicator")
  @Mapping(target = "fatherParentalTermDate", source = "fatherParentalRightTermDate")
  @Mapping(target = "sciIndexNumber", source = "clientIndexNumber")
  @Mapping(target = "motherParentalTermDate", source = "motherParentalRightTermDate")
  @Mapping(target = "soc158PlacementCode", source = "soc158PlacementCode")
  @Mapping(target = "hispUnableToDeterminateReasonCode", source = "hispanicUnableToDetermineReasonCode")
  @Mapping(target = "ethUnableToDeterminCode", source = "ethnicityUnableToDetermineReasonCode")
  @Mapping(target = "lastUpdateTimestamp", source = "lastUpdateTime")
  @Mapping(target = "lastUpdateId", source = "lastUpdateId")
  @Mapping(target = "unemployedParentCode", source = "unemployedParentCode")
  @Mapping(target = "suffixTitleDescription", source = "suffixTitleDescription")
  @Mapping(target = "socialSecurityNumberChangedCode", source = "socialSecurityNumberChangedCode")
  @Mapping(target = "socialSecurityNumber", source = "socialSecurityNumber")
  @Mapping(target = "sensivityHealthInfoOnFileIndicator", source = "sensitiveHealthInfoOnFileIndicator")
  @Mapping(target = "sensivityIndicator", source = "sensitivityIndicator")
  @Mapping(target = "secondaryLanguageType", source = "secondaryLanguageType")
  @Mapping(target = "religionType", source = "religionType")
  @Mapping(target = "primaryLanguageType", source = "primaryLanguageType")
  @Mapping(target = "primaryEthnicityType", source = "primaryEthnicityType")
  @Mapping(target = "outstandingWarrantIndicator", source = "outstandingWarrantIndicator")
  @Mapping(target = "nameType", source = "nameType")
  @Mapping(target = "namePrefixDescription", source = "namePrefixDescription")
  @Mapping(target = "militaryStatusCode", source = "militaryStatusCode")
  @Mapping(target = "materialStatusType", source = "maritalStatusType")
  @Mapping(target = "maritalCohabitatnIndicator", source = "maritalCohabitationHistoryIndicator")
  @Mapping(target = "litrateCode", source = "literateCode")
  @Mapping(target = "incapacitatedParentCode", source = "incapacitatedParentCode")
  @Mapping(target = "immigrationStatusType", source = "immigrationStatusType")
  @Mapping(target = "immigrationCountryCodeType", source = "immigrationCountryCodeType")
  @Mapping(target = "genderCode", source = "genderCode")
  @Mapping(target = "driverLicenseStateCodeType", source = "driverLicenseStateCodeType")
  @Mapping(target = "driverLicensNumber", source = "driverLicenseNumber")
  @Mapping(target = "deathReason", source = "deathReasonText")
  @Mapping(target = "deathDate", source = "deathDate")
  @Mapping(target = "creationDate", source = "creationDate")
  @Mapping(target = "confidentialityActionDate", source = "confidentialityActionDate")
  @Mapping(target = "confidentialityInEffectInd", source = "confidentialityInEffectIndicator")
  @Mapping(target = "commonMiddleName", source = "commonMiddleName")
  @Mapping(target = "commonLastName", source = "commonLastName")
  @Mapping(target = "commonFirstName", source = "commonFirstName")
  @Mapping(target = "childClientIndVar", source = "childClientIndicator")
  @Mapping(target = "birthCountryCode", source = "birthCountryCodeType")
  @Mapping(target = "birthStateCodeType", source = "birthStateCodeType")
  @Mapping(target = "birthFacilityName", source = "birthFacilityName")
  @Mapping(target = "birthDt", source = "birthDate")
  @Mapping(target = "alienRegistrationNumber", source = "alienRegistrationNumber")
  @Mapping(target = "adoptionStatusCode", source = "adoptionStatus.code")
  @Mapping(target = "identifier", source = "identifier")
  ClientDTO toClientDTO(Client client);
}
